services:
  - type: web
    name: emotion-detection-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    pythonVersion: 3.10.12
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: PYTHONUNBUFFERED
        value: "true"
    autoDeploy: true