services:
  - type: web
    name: emotion-detection-app
    env: python
    buildCommand: |
      sudo apt-get update -y
      sudo apt-get install -y libgl1-mesa-glx libglib2.0-0
      pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: PYTHONUNBUFFERED
        value: "true"
    scaling:
      minInstances: 1
      maxInstances: 1