services:
  - type: web
    name: emotion-detection-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.9
    scaling:
      minInstances: 1
      maxInstances: 1